development:
  cloud_name: <%= Rails.application.credentials[:cloud_api_name] %>
  api_key: <%= Rails.application.credentials[:cloud_api_key] %>
  api_secret: <%= Rails.application.credentials[:cloud_api_secret] %>
  secure: true

production:
  cloud_name: <%= Rails.application.credentials[:cloud_api_name] %>
  api_key: <%= Rails.application.credentials[:cloud_api_key] %>
  api_secret: <%= Rails.application.credentials[:cloud_api_secret] %>
  secure: true

test:
  cloud_name: <%= Rails.application.credentials[:cloud_api_name] %>
  api_key: <%= Rails.application.credentials[:cloud_api_key] %>
  api_secret: <%= Rails.application.credentials[:cloud_api_secret] %>
  secure: true

